### ISSUE TITLE
`impl Random` on arrays can lead to dropping uninitialized memory

### ISSUE THREAD

**Issue by JOE1994** [mersinvald/autorand-rs#5]
Hello :crab: ,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description
https://github.com/mersinvald/autorand-rs/blob/c838309507f9364ecf61553a6ae113dd720fdab9/src/lib.rs#L160-L170
`T::random()` can potentially panic (since `Random` is a public trait and users can implement it on custom types) and if it does, 
the partially initialized `array` is dropped. Thus `T::drop()` can be invoked on uninitialized memory, leading to undefined behavior.

Thank you for reviewing this issue :+1:

**Comment by mersinvald** [comment]
Thank you for pointing that out, I'll release a fixed version right away.

Great work, thanks for making Rust open-source safer

**Comment by JOE1994** [comment]
Thank you for your feedback! Would you also mind publishing a new release containing the fix to crates.io?

**Comment by mersinvald** [comment]
Yeah, doing just that
